version: '3.8'

networks:
    main-network:
        external: false
        name: main-network

services:
  postgres:
    image: postgres:14
    container_name: local_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: flow-builder
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main-network
    command: ["postgres", "-c", "listen_addresses=*"]


  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=sqs,secretsmanager,s3
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
    networks:
        - main-network


volumes:
  postgres_data:
  localstack_data:
